apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
- name: argocd-apps
  releaseName: argocd-apps
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
