applications:
- name: bootstrap
  namespace: argocd
  project: default
  source:
    repoURL: https://github.com/adilsonmenechini/gitops-argocd.git
    targetRevision: HEAD
    path: gitops/bootstrap/
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
