server:
  extraArgs:
  - --insecure
  ingress:
    enabled: true
    ingressClassName: nginx-private
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/group: Server
      gethomepage.dev/name: ArgoCD
      gethomepage.dev/description: Kubernetes Deployments
      gethomepage.dev/icon: argocd.svg
      gethomepage.dev/weight: "1"

configs:
  cm:
    kustomize.buildOptions: --enable-helm --load-restrictor LoadRestrictionsNone

