apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: nginx-ingress-controller
  releaseName: nginx-ingress-controller
  version: 9.9.4
  repo: https://charts.bitnami.com/bitnami
  valuesInline:
    service:
      type: "ClusterIP"
