apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  version: 4.9.1
  repo: https://kubernetes.github.io/ingress-nginx
  valuesInline:
    controller:
      hostPort:
        enabled: true
      terminationGracePeriodSeconds: 0
      service:
        type: "NodePort"
      watchIngressWithoutClass: true
      nodeSelector:
        ingress-ready: "true"
      tolerations:
      - effect: "NoSchedule"
        key: "node-role.kubernetes.io/master"
        operator: "Equal"
      - effect: "NoSchedule"
        key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
      publishService:
        enabled: false
      extraArgs:
        publish-status-address: "localhost"
