apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
helmCharts:
- name: ingress-nginx
  releaseName: ingress-nginx
  version: 4.9.1
  repo: https://kubernetes.github.io/ingress-nginx
  # Values files:
  valuesFile: values.yaml
  # additionalValuesFiles:
  # - values-file-1.yml
