apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: metrics-server
  releaseName: metrics-server
  version: 3.10.0
  repo: https://kubernetes-sigs.github.io/metrics-server/
  valuesInline:
    args:
    - --kubelet-insecure-tls
