apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
- name: argo-workflows
  releaseName: argo-workflows
  version: 0.40.1
  repo: https://argoproj.github.io/argo-helm
  #valuesFile: values.yaml
