apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
helmCharts:
- name: argocd
  releaseName: argo-cd
  version: 6.1.0
  repo: https://argoproj.github.io/argo-helm
  valuesFile: values.yaml
